name: Deploy to S3

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1 # あなたのS3バケットのリージョン

    - name: Deploy static files to S3
      run: aws s3 sync . s3://katsuhiro-cicd --delete # バケット名をあなたのものに置き換える

    - name: Invalidate CloudFront cache (optional)
      # CloudFrontを使っていない場合はこのステップは不要
      run: echo "CloudFront Invalidation not configured."